# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.23.1"

gem "tty-color", "~> 0.6.0"

gem "tty-font", "~> 0.5.0"

gem "tty-progressbar", "~> 0.18.2"
